
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sample_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  show-sql: true

logging:
  level:
    root: info

jwt:
  secret: 2b44b0b00fd822d8ce753e54dac3dc4e06c2725f7db930f3b9924468b53194dbccdbe23d7baa5ef5fbc414ca4b2e64700bad60c5a7c45eaba56880985582fba4
  expiration: 3600000