
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sample_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  show-sql: true

logging:
  level:
    root: info