version: '3.8'
services:
  spring-boot-app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      spring.datasource.url: jdbc:mysql://db:3306/sample_db
      spring.datasource.username: root
      spring.datasource.password: root

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: sample_db
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data: